"""Initial Schema

Revision ID: 045cb91dcd24
Revises: 
Create Date: 2026-07-19 16:09:11.377146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045cb91dcd24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=50), nullable=False),
    sa.Column('config_value', sa.Numeric(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('divisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('fine_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('rate_per_bunch_rupiah', sa.Numeric(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_fine_configurations_one_active', 'fine_configurations', ['id'], unique=True, postgresql_where=sa.text('effective_until IS NULL'))
    op.create_table('loose_fruit_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flat_percentage', sa.Numeric(), nullable=False),
    sa.Column('rate_per_kg_rupiah', sa.Numeric(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_loose_fruit_configurations_one_active', 'loose_fruit_configurations', ['id'], unique=True, postgresql_where=sa.text('effective_until IS NULL'))
    op.create_table('payroll_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_payroll_period_year_month')
    )
    op.create_table('premium_eligibility_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('basis_kg', sa.Numeric(), nullable=False),
    sa.Column('min_bunch_count', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_premium_eligibility_configurations_one_active', 'premium_eligibility_configurations', ['id'], unique=True, postgresql_where=sa.text('effective_until IS NULL'))
    op.create_table('progressive_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=False),
    sa.Column('min_kg', sa.Numeric(), nullable=False),
    sa.Column('max_kg', sa.Numeric(), nullable=True),
    sa.Column('rate_per_kg', sa.Numeric(), nullable=False),
    sa.Column('effective_from', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_progressive_tiers_active_level', 'progressive_tiers', ['tier_level'], unique=True, postgresql_where=sa.text('effective_until IS NULL'))
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('division_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('planting_year', sa.Integer(), nullable=True),
    sa.Column('area_ha', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('division_id', 'code', name='uq_division_code')
    )
    op.create_index('idx_blocks_division', 'blocks', ['division_id'], unique=False)
    op.create_table('payroll_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_period_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('point_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'point_number', name='uq_block_point')
    )
    op.create_index('idx_collection_points_block', 'collection_points', ['block_id'], unique=False)
    op.create_table('harvesters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_number', sa.String(length=30), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('division_id', sa.UUID(), nullable=True),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_number')
    )
    op.create_index('idx_harvesters_block', 'harvesters', ['block_id'], unique=False)
    op.create_index('idx_harvesters_division', 'harvesters', ['division_id'], unique=False)
    op.create_table('payroll_batch_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_batch_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_batch_id'], ['payroll_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_harvest_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('harvester_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('collection_point_id', sa.UUID(), nullable=False),
    sa.Column('harvest_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('valid_bunch_count', sa.Integer(), nullable=False),
    sa.Column('unripe_bunch_count', sa.Integer(), nullable=False),
    sa.Column('avg_bunch_weight_kg', sa.Numeric(), nullable=False),
    sa.Column('gross_tonnage_kg', sa.Numeric(), sa.Computed('valid_bunch_count * avg_bunch_weight_kg', persisted=True), nullable=True),
    sa.Column('loose_fruit_percentage_snapshot', sa.Numeric(), nullable=False),
    sa.Column('loose_fruit_rate_snapshot_rupiah', sa.Numeric(), nullable=False),
    sa.Column('loose_fruit_deduction_kg', sa.Numeric(), sa.Computed('valid_bunch_count * avg_bunch_weight_kg * loose_fruit_percentage_snapshot', persisted=True), nullable=True),
    sa.Column('loose_fruit_premium_rupiah', sa.Numeric(), sa.Computed('valid_bunch_count * avg_bunch_weight_kg * loose_fruit_percentage_snapshot * loose_fruit_rate_snapshot_rupiah', persisted=True), nullable=True),
    sa.Column('fine_mode_snapshot', sa.String(length=10), nullable=False),
    sa.Column('fine_amount_rupiah', sa.Numeric(), nullable=False),
    sa.Column('weight_deduction_kg', sa.Numeric(), sa.Computed("CASE WHEN fine_mode_snapshot = 'kg' THEN unripe_bunch_count * avg_bunch_weight_kg ELSE 0 END", persisted=True), nullable=True),
    sa.Column('net_tonnage_kg', sa.Numeric(), sa.Computed("\n        (valid_bunch_count * avg_bunch_weight_kg)\n        - (valid_bunch_count * avg_bunch_weight_kg * loose_fruit_percentage_snapshot)\n        - (CASE WHEN fine_mode_snapshot = 'kg' THEN unripe_bunch_count * avg_bunch_weight_kg ELSE 0 END)\n    ", persisted=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=100), nullable=True),
    sa.Column('payroll_period_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_point_id'], ['collection_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['harvester_id'], ['harvesters.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_harvest_block', 'daily_harvest_records', ['block_id'], unique=False)
    op.create_index('idx_daily_harvest_harvester_date', 'daily_harvest_records', ['harvester_id', 'harvest_date'], unique=False)
    op.create_index('idx_daily_harvest_period', 'daily_harvest_records', ['payroll_period_id'], unique=False)
    op.create_table('payroll_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_batch_id', sa.UUID(), nullable=False),
    sa.Column('harvester_id', sa.UUID(), nullable=False),
    sa.Column('total_valid_bunch_count', sa.Integer(), nullable=False),
    sa.Column('total_unripe_bunch_count', sa.Integer(), nullable=False),
    sa.Column('total_net_tonnage_kg', sa.Numeric(), nullable=False),
    sa.Column('total_loose_fruit_premium_rupiah', sa.Numeric(), nullable=False),
    sa.Column('fine_mode_used', sa.String(length=10), nullable=False),
    sa.Column('total_fine_rupiah', sa.Numeric(), nullable=False),
    sa.Column('total_tier_premium_rupiah', sa.Numeric(), nullable=False),
    sa.Column('total_net_pay_rupiah', sa.Numeric(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['harvester_id'], ['harvesters.id'], ),
    sa.ForeignKeyConstraint(['payroll_batch_id'], ['payroll_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_batch_id', 'harvester_id', name='uq_payroll_batch_harvester')
    )
    op.create_index('idx_payroll_summaries_batch', 'payroll_summaries', ['payroll_batch_id'], unique=False)
    op.create_table('payroll_tier_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_summary_id', sa.UUID(), nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=False),
    sa.Column('kg_in_tier', sa.Numeric(), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(), nullable=False),
    sa.Column('subtotal_rupiah', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['payroll_summary_id'], ['payroll_summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_tier_details')
    op.drop_index('idx_payroll_summaries_batch', table_name='payroll_summaries')
    op.drop_table('payroll_summaries')
    op.drop_index('idx_daily_harvest_period', table_name='daily_harvest_records')
    op.drop_index('idx_daily_harvest_harvester_date', table_name='daily_harvest_records')
    op.drop_index('idx_daily_harvest_block', table_name='daily_harvest_records')
    op.drop_table('daily_harvest_records')
    op.drop_table('payroll_batch_history')
    op.drop_index('idx_harvesters_division', table_name='harvesters')
    op.drop_index('idx_harvesters_block', table_name='harvesters')
    op.drop_table('harvesters')
    op.drop_index('idx_collection_points_block', table_name='collection_points')
    op.drop_table('collection_points')
    op.drop_table('payroll_batches')
    op.drop_index('idx_blocks_division', table_name='blocks')
    op.drop_table('blocks')
    op.drop_index('uq_progressive_tiers_active_level', table_name='progressive_tiers', postgresql_where=sa.text('effective_until IS NULL'))
    op.drop_table('progressive_tiers')
    op.drop_index('uq_premium_eligibility_configurations_one_active', table_name='premium_eligibility_configurations', postgresql_where=sa.text('effective_until IS NULL'))
    op.drop_table('premium_eligibility_configurations')
    op.drop_table('payroll_periods')
    op.drop_index('uq_loose_fruit_configurations_one_active', table_name='loose_fruit_configurations', postgresql_where=sa.text('effective_until IS NULL'))
    op.drop_table('loose_fruit_configurations')
    op.drop_index('uq_fine_configurations_one_active', table_name='fine_configurations', postgresql_where=sa.text('effective_until IS NULL'))
    op.drop_table('fine_configurations')
    op.drop_table('divisions')
    op.drop_table('app_config')
    # ### end Alembic commands ###
