"""add tier_status to daily_harvest_records

Revision ID: debef53c3422
Revises: f6a91dc81754
Create Date: 2026-07-15 18:48:37.885674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'debef53c3422'
down_revision: Union[str, Sequence[str], None] = 'f6a91dc81754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_harvest_records', sa.Column('tier_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_harvest_records', 'tier_status')
    # ### end Alembic commands ###
