"""Initial schema

Revision ID: f6a91dc81754
Revises: 
Create Date: 2026-07-15 13:18:39.936887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a91dc81754'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=50), nullable=False),
    sa.Column('config_value', sa.Numeric(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('daily_harvest_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('harvest_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('harvester_name', sa.String(length=100), nullable=False),
    sa.Column('input_total_bunches', sa.Integer(), nullable=False),
    sa.Column('input_avg_bunch_weight', sa.Numeric(), nullable=False),
    sa.Column('input_unripe_penalty', sa.Numeric(), nullable=False),
    sa.Column('calc_total_tonnage', sa.Numeric(), nullable=False),
    sa.Column('calc_loose_fruit_kg', sa.Numeric(), nullable=False),
    sa.Column('calc_net_ffb', sa.Numeric(), nullable=False),
    sa.Column('premium_loose_fruit', sa.Numeric(), nullable=False),
    sa.Column('premium_ffb', sa.Numeric(), nullable=False),
    sa.Column('total_final_premium', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progressive_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=False),
    sa.Column('min_kg', sa.Numeric(), nullable=False),
    sa.Column('max_kg', sa.Numeric(), nullable=True),
    sa.Column('rate_per_kg', sa.Numeric(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_level')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progressive_tiers')
    op.drop_table('daily_harvest_records')
    op.drop_table('app_config')
    # ### end Alembic commands ###
